### ISSUE TITLE
cannot export CHOP in performance mode

### ISSUE THREAD

**Issue by t0mekk** [Richard-Burns/SimpleMixer#10] opened 2018-03-16 22:39 UTC
not sure if it's experimental version related issue, but when perform window is set to '**always on top'** you cannot export CHOPs to custom parameters.

**Comment by Richard-Burns** [comment] 2018-03-17 14:03
Yeah this looks like a touchdesigner bug or they may have done it intentionally by design. I'll report it in bugs forum. If it is by design that's annoying as I'd need to make some kind of drag n drop for the parameters manually. Lets see what Derivative say about that before I do anything. Will leave this issue open for now.

**Comment by Richard-Burns** [comment] 2018-04-10 14:24
This bug is now fixed in TouchDesigner and SimpleMixer 0.3.5 is back to always being on top.

**Closed by Richard-Burns** 2018-04-10 14:24 UTC
